[workspace]
members = [
  "applications/server",
  "applications/client-backup-cli", "crates/proto-control", "crates/opendal-iroh",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"

