[package]
name = "proto-control"
version = "0.1.0"
edition.workspace = true

[dependencies]
iroh = "0.92.0"
iroh-blobs = "0.94.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
snafu = "0.8.9"
tracing = "0.1.41"

[lints]
workspace = true
