[package]
name = "client-backup-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
opendal-iroh = { path = "../../crates/opendal-iroh" }

[lints]
workspace = true
